.TH FCONF2* 1 "fconf2*" "04 April 2001" "Husky - Portable Fidonet Software"
.SH NAME
fconf2* \- Converts fidoconfig to another format
.SH SYNOPSIS
.B fconf2golded, fconf2msged, fconf2aquaed, fconf2fidogate,
.B fconf2squish
/path/to/new/config [/path/to/defaultconfig]
.SH "DESCRIPTION"
.B fconf2*
Converts fidoconfig to config for another Programm.
.sp 2
.B fconf2golded
produces output for GoldED.
.br
.B fconf2msged
produces output for MsgED.
.br
.B fconf2aquaed
produces output for AquaED.
.br
.B fconf2fidogate
produces output for Fidogate.
.br
.B fconf2squish
produces output for Squish.
.br
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B [/path/to/new/config]
Name of output file.
.br
.B [/path/to/defaultconfig]
If you specify a defaultconfig there will be an include for it in the new
config. Useful for some Defaults.
.B NOT FOR MSGED.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/etc/fido/config   'u
\fI/etc/fido/config\fR  Default Fidoconfig.
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.physcip.uni-stuttgart.de/team.html.
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).

