.TH LINKEDTO 1 "linkedto" "04 April 2001" "Husky - Portable Fidonet Software"
.SH NAME
linkedTo \- Shellscript to show linked Areas
.SH SYNOPSIS
.B linkedto
FTN-address
.SH "DESCRIPTION"
.B linkedto
is a small Shell-Script which shows to which Areas the given Address is
linked to. Support included files.
.br
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B FTN-address
The Address for the Information.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/etc/fido/config   'u
\fI/etc/fido/config\fR
.ta \w'/usr/local/etc/fido/config   'u
\fI/usr/local/etc/fido/config\fR  Default Fidoconfig.
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.physcip.uni-stuttgart.de/team.html.
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).
.PP
Updated by Stas Degteff 2:5080/102 <g@grumbler.org>

