.TH LINKED 1 "linked" "10 January 2003" "Husky - Portable Fidonet Software"
.SH NAME
linked \- program to show linked areas for link
.SH SYNOPSIS
.B linked
<FTN-address> [<FTN-address> ...]
.SH "DESCRIPTION"
.B linked
is a small program which shows to which Areas the given Address(es) is
linked to. Support included files.
.br
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B FTN-address
The Address for the Information.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/etc/fido/config   'u
\fI/etc/fido/config\fR
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.sourceforge.net/team.html.
.SH AUTHOR
This manual page was written by Pavel Andreew <pavel@collage.etel.ru>,
adopted from linkedto.1.
