.TH TPARSER 1 "tparser" "04 April 2001" "Husky - Portable Fidonet Software"
.SH NAME
tparser \- Parses Fidoconfig
.SH SYNOPSIS
.B tparser
[/path/to/fido/config]
.SH "DESCRIPTION"
.B tparser
Checks your Fidoconfig for errors and gives you some hints to solve the
problems. If
.B tparser
finds an error \fINO\fR Huskyprogramm will work !
.br
.sp 2
This manual page was written for the Debian GNU/Linux distribution
because the original program does not have a manual page.
.SH OPTIONS
.B [/path/to/fido/config]
Optional path to Fidoconfig. If left blank the builtin default will be used.
.br
.B --help
Print command line parameters
.SH "RETURN VALUE"
.B 0
if there is no error.
.SH ERRORS
.B 1
if there is an error.
.SH FILES
.br
.nf
.\" set tabstop to longest possible filename, plus a wee bit
.ta \w'/etc/fido/config   'u
\fI/etc/fido/config\fR  Default Fidoconfig.
.SH NOTES
All Husky-Software is written by various developers. For detailed information
about the Husky-Team take a look at 
http://husky.physcip.uni-stuttgart.de/team.html.
.SH AUTHOR
This manual page was written by Joerg Jaspert (JJ) <joerg@goliathbbs.dnsalias.net>,
for the Debian GNU/Linux system (but may be used by others).

