/******************************************************************************
 * FIDOCONFIG --- library for fidonet configs
 ******************************************************************************
 * fconf2jt - convert fidoconfig to Just Tosser's config
 * Copyright (C) 2002 Dmitriy Stepanov, 2:5070/251
 *
 * This file is part of FIDOCONFIG.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License as published by the Free Software Foundation; either
 * version 2 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; see file COPYING. If not, write to the Free
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *****************************************************************************
 * $Id$
 */

#include <stdlib.h>
#include <string.h>

#include "fidoconf.h"
#include "common.h"

#include <smapi/unused.h>

int writeArea(FILE *f, s_area *area, int type) {

 fprintf(f, "Area \"%s\"\n", area->areaName);

 if (area->description != NULL)
  fprintf(f, " Desc \"%s\"\n", area->description);

 fprintf(f, " Base ");

 switch (type) 
 {
  case 0: fprintf(f, "Netmail ");
       break;
  case 1: fprintf(f, "Local ");
       break;
  case 2: fprintf(f, "Echomail ");
 }

 switch (area->msgbType)
 {
  case MSGTYPE_SDM: fprintf(f, "*.msg ");
       break;
  case MSGTYPE_SQUISH: fprintf(f, "Squish ");
       break;
  case MSGTYPE_JAM: fprintf(f, "Jam ");
       break;
  case MSGTYPE_PASSTHROUGH: fprintf(f, "Passthrough \"\"\n");
 }

 if (area->msgbType != MSGTYPE_PASSTHROUGH)
  fprintf(f,"\"%s\"\n",area->fileName);

 if (area->downlinkCount > 0 && area->downlinks[0]->link->autoAreaCreate)
  fprintf(f, " Uplink %s\n", aka2str(area->downlinks[0]->link->hisAka));

 if (area->group)
  fprintf(f, " aeGroup \"%s\"\n", area->group);

  fprintf(f,";\n");

   return 0;
}

int writeLink(FILE *f, s_link *link, s_fidoconfig *config)
{
  int i;
  s_area *area;

  if (link->defaultPwd != NULL)
  {
   fprintf(f, "Address %s\n", aka2str(link->hisAka));
   fprintf(f, " Aka %s\n", aka2str(link->ourAka[0]));
   fprintf(f, " InPassword \"%s\"\n", link->defaultPwd);
   fprintf(f, " OutPassword \"%s\"\n", link->defaultPwd);
   fprintf(f, " Archiver \"%s\"\n", strUpper(link->packerDef->packer));
   switch (link->linkBundleNameStyle)
   {
    case eAmiga: fprintf(f, " Mode \"ASO\"\n");
         break;
    default: fprintf(f, " Mode \"BSO\"\n");
   } 

   if (link->autoAreaCreate)
   {
     fprintf(f, " AutoCreate Yes\n");
     fprintf(f, "   AutoCreateFormat Passthrough \"\"\n");
     fprintf(f, " AreafixPassword \"%s\"\n",link->areaFixPwd);
   }
   
   for (i=0; i<config->echoAreaCount; i++)
   {
    area = &(config->echoAreas[i]);

    // FIXME: All links by default can Read and Write to EchoArea
    if (isLinkOfArea(link, area))
     fprintf(f, " Area RW \"%s\"\n",area->areaName);
   }

   fprintf(f, ";\n");
  }
  return 0;
}

void GenerateJTconfigs(s_fidoconfig *config, char *areafile, char *linksfile)
{
  FILE *areas;
  FILE *links;
  s_area *area;
  s_link *link;
  int i;

  areas = fopen(areafile, "a+");

  if (areas != NULL)
  {

   fprintf(areas,";\n; This file generated by fconf2jt\n;\n");

   fprintf(areas,";\n; Netmail areas\n;\n");

   for (i=0; i<config->netMailAreaCount; i++)
   {
    area = &(config->netMailAreas[i]);
    writeArea(areas, area, 0);
   }

   fprintf(areas,";\n; Local areas\n;\n");

   for (i=0; i<config->localAreaCount; i++)
   {
    area = &(config->localAreas[i]);
    writeArea(areas, area, 1);
   }

   fprintf(areas,";\n; Echomail areas\n;\n");
   
   for (i=0; i<config->echoAreaCount; i++)
   {
    area = &(config->echoAreas[i]);
    writeArea(areas, area, 2);
   }     
   fprintf(areas, "; oef");
   fclose(areas);
  } 
  else printf("Could not write areas.ctl\n");

  links = fopen(linksfile, "a+");

  if (links != NULL)
  {
   fprintf(links,";\n; This file generated by fconf2jt\n;\n");
    
   for (i=0; i<config->linkCount; i++) 
   {
    link = &(config->links[i]);
    writeLink(links, link, config);
   } 

   fprintf(areas, "; oef");
   fclose(links);
  }
  else printf("Could not write links.ctl\n");

}

int main (int argc, char *argv[]) {
  
   s_fidoconfig *config;

   printf("fconf2jt\n");
   printf("--------\n");
   if (argc < 3) {
      printf("\nUsage:\n");
      printf("   fconf2jt <areas.ctl> <links.ctl> [<default.cfg>]\n");
      printf("   to generate areas and links config files");
      printf("\nExample:\n");
      printf("   fconf2jt areas.ctl links.ctl d:\\ftn\\htp\\config.cfg\n\n");
      return 1;
      }

   printf("Generating Config-file");

   if (argv[3] != NULL)
   {
    config = readConfig(argv[3]);
    if (config!= NULL)
     { 
      GenerateJTconfigs(config, argv[1], argv[2]);
      disposeConfig(config);
     }
   }
   else 
   {
    config = readConfig(NULL);
    if (config!= NULL) 
     { 
      GenerateJTconfigs(config, argv[1], argv[2]);
      disposeConfig(config);
     }
   }
   return 1;
}

