#!/usr/bin/perl
@Id=split(" ", '$Id$');
# Generate binkd and ifcico password files from fidoconfig
# (c) Copyleft Stas Degteff 2:5080/102@fidonet

use Getopt::Std;

my %passwords; # pairs FTN_address => password

&work;

sub work{

  my %opts;
  getopts('vhb:i:', \%opts);

  if( $opts{"v"} ){
    &VERSION_MESSAGE;
  }

  if( (($opts{"b"} eq "") and ($opts{"i"} eq "")) or $opts{"h"} ){
    &HELP_MESSAGE;
  }

  if( $#ARGV < 0 ){
    my $varfidoconfig = (grep( /^FIDOCONFIG$/i, keys(%ENV) ))[0];
    my $fidoconfig = $ENV{$varfidoconfig} if( "$varfidoconfig" ne "" );
    parse($fidoconfig);
  }else{
    foreach my $fidoconfig (@ARGV){
      parse($fidoconfig);
    }
  }

  if( $opts{"b"} ){
    if( ! open BINKDPWD, ">".$opts{"b"} ) {
      print STDERR "Can't write to ",$opts{"b"},", skip ($!)\n";
    }else{
      foreach my $addr (keys(%passwords)){
        print BINKDPWD $addr, " ", $passwords{$addr}, "\n";
      }
      close BINKDPWD;
    }
  }

  if( $opts{"i"} ){
    if( ! open IFMAILPWD, ">".$opts{"i"} ) {
      print STDERR "Can't write to ",$opts{"i"},", skip ($!)\n";
    }else{
      foreach my $addr (keys(%passwords)){
        print IFMAILPWD "password ",$addr, " ", $passwords{$addr}, "\n";
      }
      close IFMAILPWD;
    }
  }

} # sub work

######### Subroutines #
sub parse{
  my $aka, @includes;
  if( open(CONFIG,$_[0]) ){
    print "Parsing file $_[0]\n";
    while(<CONFIG>){
      s/^[ \t]//g;
      if( $_ =~ /^link\s/i ){ undef $aka; next; }
      if( $_ =~ /^aka\s+(\S+)/i ){ $aka=$1; next; }
      if( $_ =~ /^password\s+(\S+)/i ){ if($passwords{$aka} eq ""){$passwords{$aka}=$1} next;  }
      if( $_ =~ /^sessionPwd\s+(\S+)/i ){ $passwords{$aka}=$1; next; }
      if( $_ =~ /^include\s+(\S+)/i ){ push( @includes, $1 ); }
    }
    close CONFIG;
    foreach (@includes){ parse($_); }
  }else{
    print STDERR "Can't open ", $_[0], ", skip ($!)\n";
  }
}


sub VERSION_MESSAGE(){
print <<VVV;
genmailerpwd $Id[2] - A perl script to generate binkd and ifcico password files from fidoconfig
(c) Copyleft Stas Degteff 2:5080/102@fidonet
Licence: GPL v.3
VVV
exit;
}

sub HELP_MESSAGE(){
print <<UUU;
genmailerpwd - A perl script to generate binkd and ifcico password files from fidoconfig

Synopsys
   genmailerpwd [-b /fido/binkd.passwd] [-i /fido/ifcico.passwd]
       Use enviroment variable FIDOCONFIG pointedto fidoconfig file, write binkd passwords "/fido/binkd.passwd" and ifcico passwords file "/fido/ifcico.passwd"
   genmailerpwd [-b /fido/binkd.passwd] [-i /fido/ifcico.passwd] /fido/links
       Use fidoconfig file "/fido/links", write binkd passwords "/fido/binkd.passwd" and ifcico passwords file "/fido/ifcico.passwd"
   genmailerpwd -v
       Print version information and exit.
   genmailerpwd -h
   genmailerpwd
       Print this message and exit.

UUU
exit(1);
}
