# $Id$
#
# Object files lists for all platforms
# include into makefile.inc (and other makefiles)

LOBJS = common$(OBJ) fidoconf$(OBJ) line$(OBJ) cfg$(OBJ) findtok$(OBJ) areatree$(OBJ) afixcmd$(OBJ) afixcmn$(OBJ) arealist$(OBJ) version$(OBJ) grptree$(OBJ)

OBJS = $(LOBJS) fc2binkd$(OBJ) fc2msged$(OBJ) fc2ged$(OBJ) fc2aed$(OBJ) fc2fgate$(OBJ) fc2sq$(OBJ) fc2tor$(OBJ) fecfg146$(OBJ) fecfg2fc$(OBJ) linked$(OBJ)

PROGRAMS= tparser$(EXE) linked$(EXE) $(FCONF2BINKD)$(EXE) $(FCONF2MSGED)$(EXE) $(FCONF2AQUAED)$(EXE) $(FCONF2FIDOGATE)$(EXE) $(FCONF2GOLDED)$(EXE) $(FCONF2SQUISH)$(EXE) $(FCONF2TORNADO)$(EXE) $(FECFG2FCONF)$(EXE)