# Settings for AIX

# There is no makefile for AIX any more as we don't have a AIX machine to
# test things any more.

# To build husky on AIX with gcc, try to use makefile.lnx, but if you
# are using IBM's C compiler, add the following parameter to the CFLAGS:
#
#     -qcpluscmt
#
# This will allow "//" style comments in ANSI C # source code. 

